# Generated by Django 3.2.13 on 2022-05-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220519_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_health_decreased',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_round',
        ),
    ]
