# Generated by Django 3.2.13 on 2022-05-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220521_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_opponent_clone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opponents', to='api.player'),
        ),
    ]
